// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAhtcD-xuhEuYRqza2TMUpwid8zjiut5Y',
    appId: '1:585982609265:web:34ecb665c3d0469bcdd8d0',
    messagingSenderId: '585982609265',
    projectId: 'login-registration2709',
    authDomain: 'login-registration2709.firebaseapp.com',
    storageBucket: 'login-registration2709.appspot.com',
    measurementId: 'G-W6P51GMHQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeD-0JJ1gSBQEOKJSaz0vQttlJgy0KB7E',
    appId: '1:585982609265:android:0b8df8833b9def2fcdd8d0',
    messagingSenderId: '585982609265',
    projectId: 'login-registration2709',
    storageBucket: 'login-registration2709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaSCWdUEHcIkub_gjGorRmBC28Brta1iM',
    appId: '1:585982609265:ios:a34490a8556b0541cdd8d0',
    messagingSenderId: '585982609265',
    projectId: 'login-registration2709',
    storageBucket: 'login-registration2709.appspot.com',
    iosClientId:
        '585982609265-6qj8fspeaf4ejmt7tficschpju7q2aha.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaSCWdUEHcIkub_gjGorRmBC28Brta1iM',
    appId: '1:585982609265:ios:a34490a8556b0541cdd8d0',
    messagingSenderId: '585982609265',
    projectId: 'login-registration2709',
    storageBucket: 'login-registration2709.appspot.com',
    iosClientId:
        '585982609265-6qj8fspeaf4ejmt7tficschpju7q2aha.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
